"""
Pages/what_would_you_do.py
Read Between The Lines — 3-phase desire profile quiz.

Scenarios come from two sources, both via AI:
  1. Reddit posts (fetched live, question generated by GPT-4o-mini)
  2. GPT-4o-mini invents fresh scenarios from scratch to fill any gaps

No pre-written scenario bank. Everything is generated.
All prompts are gender-neutral and orientation-inclusive.

Community Pulse: after answering each question the user sees an anonymous
breakdown of how other ViceVault users responded — with the most
surprising stat called out explicitly.
"""

import hashlib
import streamlit as st
import json
import random
import time
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor, as_completed

# ─── CONSTANTS ────────────────────────────────────────────────────────────────

SUBREDDITS = ["sex", "nonmonogamy", "confessions", "trueoffmychest"]

TABOO_KEYWORDS = [
    "threesome", "3some", "open relationship", "swinger", "polyamory",
    "fantasy", "attracted to", "cheated", "affair", "tempted",
    "another person", "someone else", "bring someone", "experiment",
    "never told anyone", "taboo", "forbidden", "want to try",
    "nonmonogamy", "open marriage", "group", "voyeur",
    "fmf", "mfm", "confession", "told my partner",
    "we tried", "we talked about",
]

MIN_SCORE   = 30
MIN_LENGTH  = 100
POST_COUNT  = 7
TEXT_CUTOFF = 200

ALL_PLATFORM_CATEGORIES = [
    "18-25", "60FPS", "AI", "Amateur", "Anal", "Arab", "Asian", "Babe",
    "Babysitter (18+)", "BBW", "Behind The Scenes", "Big Ass", "Big Dick",
    "Big Tits", "Bisexual Male", "Blonde", "Blowjob", "Bondage", "Brazilian",
    "British", "Brunette", "Bukkake", "Cartoon", "Casting", "Celebrity",
    "College (18+)", "Compilation", "Cosplay", "Creampie", "Cuckold",
    "Cumshot", "Czech", "Deepthroat", "Double Penetration", "Ebony", "Euro",
    "Exclusive", "Feet", "Female Orgasm", "Fetish", "Fingering", "Fisting",
    "French", "Funny", "Gaming", "Gangbang", "German", "Handjob", "Hardcore",
    "HD Porn", "Hentai", "Indian", "Interactive", "Interracial", "Italian",
    "Japanese", "Korean", "Latina", "Lesbian", "Massage", "Masturbation",
    "Mature", "MILF", "Muscular Men", "Music", "Old/Young (18+)", "Orgy",
    "Parody", "Party", "Pissing", "Podcast", "Popular With Women", "Pornstar",
    "POV", "Public", "Pussy Licking", "Reaction", "Reality", "Red Head",
    "Role Play", "Romantic", "Rough Sex", "Russian", "School (18+)", "SFW",
    "Small Tits", "Smoking", "Solo Female", "Solo Male", "Squirt",
    "Step Fantasy", "Strap On", "Striptease", "Tattooed Women", "Threesome",
    "Toys", "Transgender", "Verified Amateurs", "Verified Couples",
    "Verified Models", "Vintage", "Virtual Reality", "Webcam",
]

FALLBACK_POSTS = [
    {
        "sub": "r/relationship_advice", "avatar": "T", "user": "throwaway_82947",
        "title": "My partner and I accidentally started a conversation we can't take back",
        "text": "We talked for two hours about things we'd never said out loud before.",
        "upvotes": "14.2k", "comments": "832", "time": "6 hours ago",
        "url": "https://reddit.com/r/relationship_advice", "flair": "Long Post",
    },
    {
        "sub": "r/confessions", "avatar": "A", "user": "anon_user_2291",
        "title": "I described what happens in our bedroom to my best friend",
        "text": "They asked if I'd describe what it's actually like. I did. In detail.",
        "upvotes": "9.7k", "comments": "1.2k", "time": "2 days ago",
        "url": "https://reddit.com/r/confessions", "flair": "True Story",
    },
    {
        "sub": "r/trueoffmychest", "avatar": "S", "user": "strangebutreal",
        "title": "My partner and I spent four hours talking about a hypothetical last night",
        "text": "'If you could add anyone to our relationship for one night, who?' They answered.",
        "upvotes": "18.3k", "comments": "976", "time": "5 hours ago",
        "url": "https://reddit.com/r/trueoffmychest", "flair": "Personal",
    },
    {
        "sub": "r/sex", "avatar": "M", "user": "maybe_mistakes",
        "title": "My partner said my fantasy made them feel like they weren't enough",
        "text": "I told them about a recurring fantasy. They got quiet.",
        "upvotes": "22.1k", "comments": "3.4k", "time": "1 day ago",
        "url": "https://reddit.com/r/sex", "flair": "Advice",
    },
    {
        "sub": "r/nonmonogamy", "avatar": "L", "user": "late_night_post_88",
        "title": "My friend accidentally sent my partner my text about wanting an open relationship",
        "text": "They texted me three seconds later. 'Why haven't you just told me this?'",
        "upvotes": "31.5k", "comments": "2.1k", "time": "3 days ago",
        "url": "https://reddit.com/r/nonmonogamy", "flair": "Story",
    },
    {
        "sub": "r/confessions", "avatar": "W", "user": "wontusemyname",
        "title": "UPDATE: We did it. Here's the honest version.",
        "text": "The hardest part was the three days before, not the night itself.",
        "upvotes": "19.4k", "comments": "1.1k", "time": "2 days ago",
        "url": "https://reddit.com/r/confessions", "flair": "Update",
    },
    {
        "sub": "r/sex", "avatar": "N", "user": "nightowl_anon",
        "title": "Most couples don't discuss threesomes because they're scared of the answer",
        "text": "Either answer changes things. So most people carry the question for years.",
        "upvotes": "8.9k", "comments": "2.3k", "time": "12 hours ago",
        "url": "https://reddit.com/r/sex", "flair": "Discussion",
    },
]

RESULT_TYPES = [
    {
        "min": 0, "max": 10, "icon": "🔒", "name": "Closed Garden",
        "meta": "Yours. Only yours. Period.",
        "hook": "You answered every single one the same way. That consistency either means total clarity — or a story you haven't told yourself yet.",
        "signal": "You're not curious about the scenarios. You're protective of something.",
        "tell": "The question that probably landed hardest was one you dismissed fast.",
    },
    {
        "min": 11, "max": 22, "icon": "🌿", "name": "Quietly Curious",
        "meta": "The thought has crossed your mind. More than once.",
        "hook": "You played it safe on the ones that felt risky. But you didn't close the door all the way on any of them.",
        "signal": "There's a gap between what you'd say out loud and what you actually thought reading these.",
        "tell": "Someone who knows you well would not be entirely surprised by your score.",
    },
    {
        "min": 23, "max": 35, "icon": "🌙", "name": "The Open Door",
        "meta": "You've thought this through. Seriously.",
        "hook": "You've been here before — in your head, at least. These scenarios didn't shock you. They felt familiar.",
        "signal": "The gap between where you are and where you want to be is mostly just one honest conversation.",
        "tell": "You know which scenario you'd actually say yes to if the circumstances were right.",
    },
    {
        "min": 36, "max": 44, "icon": "🔺", "name": "Already Decided",
        "meta": "The question isn't whether. It's when.",
        "hook": "You didn't hesitate on the ones that matter. That's not impulsiveness — that's someone who's done the work already.",
        "signal": "You're past theory. The only thing between you and acting on this is logistics.",
        "tell": "You probably already know who you'd want in the room.",
    },
    {
        "min": 45, "max": 999, "icon": "⚡", "name": "The Third Is Already Picked",
        "meta": "You know exactly who. They probably know too.",
        "hook": "You read these like someone reading their own journal entries. Not recognition — confirmation.",
        "signal": "This isn't curiosity. This is inventory.",
        "tell": "The most interesting question for you isn't what — it's what you're still waiting for.",
    },
]

# Phase 2: escalating hidden desire statements — starts softer, goes deeper
HIDDEN_DESIRE_QUESTIONS = [
    # Tier 1 — warm up (low stakes, normalising)
    {"id": "hd_01", "signal": "verbal_latent", "tier": 1,
     "text": "Words matter to you in bed. The right thing said at the right moment does more than most physical acts."},
    {"id": "hd_02", "signal": "desired_intensity", "tier": 1,
     "text": "Someone wanting you badly enough to lose a little composure — that does something for you."},
    {"id": "hd_03", "signal": "authentic_exposure", "tier": 1,
     "text": "You're drawn to the idea of being completely seen — no performance, no holding back — and having that land well."},

    # Tier 2 — building
    {"id": "hd_04", "signal": "power_dynamic_latent", "tier": 2,
     "text": "A scene in a film with a specific power dynamic between two characters — nothing explicit, just the energy — makes you shift in your seat."},
    {"id": "hd_05", "signal": "archetype_attraction", "tier": 2,
     "text": "There's a specific kind of person — not necessarily a look — whose presence makes you immediately wonder what they'd be like."},
    {"id": "hd_06", "signal": "stranger_context", "tier": 2,
     "text": "A stranger in a specific setting — a hotel bar, a long flight, a house party — and the scenario almost writes itself before you stop it."},

    # Tier 3 — getting specific
    {"id": "hd_07", "signal": "dom_latent", "tier": 3,
     "text": "You've thought about being completely in charge — every decision, every pace, every permission. And you liked it."},
    {"id": "hd_08", "signal": "sub_latent", "tier": 3,
     "text": "You've thought about having zero say — someone else setting the terms entirely, and you just going with it. Genuinely."},
    {"id": "hd_09", "signal": "shame_adjacent_arousal", "tier": 3,
     "text": "You've encountered something — a video, a story, a thought — that turned you on and your first instinct was to be embarrassed about it."},
    {"id": "hd_10", "signal": "exhib_latent", "tier": 3,
     "text": "The idea of being watched — even hypothetically, even just once — is more interesting to you than you typically let on."},

    # Tier 4 — the ones people don't usually name
    {"id": "hd_11", "signal": "hidden_fantasy_present", "tier": 4,
     "text": "You have a fantasy you've never told anyone. Not because it's wrong — because saying it out loud would make it real in a way you're not sure you're ready for."},
    {"id": "hd_12", "signal": "group_latent", "tier": 4,
     "text": "You've wondered, seriously, what it would be like with more than one person involved. Not as a passing thought — as an actual mental image."},
    {"id": "hd_13", "signal": "taboo_draw", "tier": 4,
     "text": "There's a specific flavour of taboo — not harmful, just forbidden — that you keep coming back to even when you tell yourself you're not that interested."},

    # Tier 5 — the ones that catch people off guard
    {"id": "hd_14", "signal": "elaborated_fantasy", "tier": 5,
     "text": "You've had a fantasy so specific and detailed — names, setting, sequence — that you surprised yourself when you noticed how mapped-out it already was."},
    {"id": "hd_15", "signal": "unnamed_fixation", "tier": 5,
     "text": "There's something specific you've never done but think about more than makes sense given how rarely you'd admit to it."},
]

HD_OPTS = [
    ("nope",     "Not me",                    0),
    ("maybe",    "A little, maybe",           1),
    ("yes",      "Yeah — that's accurate",    2),
    ("strongly", "More than I'd usually say", 3),
]
HD_OPT_LABELS = [label for _, label, _ in HD_OPTS]
HD_OPT_IDS    = [oid   for oid, _, _ in HD_OPTS]

# Transition messages between phases — designed to create anticipation
PHASE_TRANSITIONS = {
    "to_hidden_desires": [
        "Phase 1 read how you react. Phase 2 goes after what you don't usually name.",
        "The scenarios showed your surface. What comes next goes deeper.",
        "You answered the situations. Now it gets more personal.",
    ],
    "to_profile": [
        "You answered everything. Now it gets put together.",
        "Reading your answers back against each other.",
        "The pattern is clearer than you probably expected.",
    ],
}


# ─── CSS ──────────────────────────────────────────────────────────────────────

def inject_css():
    st.html("""
<link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700&family=Bebas+Neue&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">
<style>
:root {
  --bg:#0a0a0b; --surface:#111114; --card:#18181d; --border:#2a2a35;
  --lime:#c6ff00; --magenta:#ff2d78; --cyan:#00e5ff; --amber:#ffb300;
  --text:#f0f0f5; --muted:#5a5a72; --soft:#9090aa;
}
.stApp { background:var(--bg) !important; }
section[data-testid="stMain"] { background:var(--bg) !important; }
section.main .block-container { padding-top:2rem !important; max-width:820px !important; }
section[data-testid="stSidebar"] { background:#0d0d10 !important; border-right:1px solid var(--border) !important; }
section[data-testid="stSidebar"] * { color:#c8c8d8 !important; }
section[data-testid="stSidebar"] .stButton > button {
  background:transparent !important; border:1px solid var(--border) !important;
  color:#c8c8d8 !important; border-radius:4px !important;
  font-family:'Space Mono',monospace !important; font-size:11px !important;
  letter-spacing:1px !important; text-transform:uppercase !important;
}
section[data-testid="stSidebar"] .stButton > button:hover {
  background:#1a1a20 !important; border-color:var(--lime) !important;
  color:var(--lime) !important; box-shadow:none !important;
}
.stButton > button {
  background:transparent !important; color:var(--soft) !important;
  border:1px solid var(--border) !important; border-radius:3px !important;
  font-family:'Space Mono',monospace !important; font-size:10px !important;
  letter-spacing:1.5px !important; text-transform:uppercase !important;
  transition:all 0.15s !important; box-shadow:none !important;
}
.stButton > button:hover { border-color:var(--lime) !important; color:var(--lime) !important; }
.stButton > button[kind="primary"] {
  background:var(--magenta) !important; color:#fff !important;
  border-color:var(--magenta) !important; font-weight:700 !important;
}
.stButton > button[kind="primary"]:hover {
  background:#ff5590 !important; box-shadow:0 0 20px rgba(255,45,120,0.25) !important;
}
.stButton > button:disabled { opacity:0.35 !important; cursor:not-allowed !important; }
.stProgress > div > div > div { background:var(--magenta) !important; }
#MainMenu { visibility:hidden; } footer { visibility:hidden; }
div[data-testid="stRadio"] > label { display:none !important; }
div[data-testid="stRadio"] > div { gap:8px !important; flex-direction:column !important; }
div[data-testid="stRadio"] > div > label {
  background:var(--card) !important; border:1px solid var(--border) !important;
  border-radius:3px !important; padding:12px 16px !important;
  font-family:'DM Sans',sans-serif !important; font-size:13px !important;
  color:var(--soft) !important;
  cursor:pointer !important; transition:all 0.15s !important; width:100% !important;
  line-height:1.55 !important;
}
div[data-testid="stRadio"] > div > label:hover {
  border-color:var(--lime) !important; color:var(--text) !important;
  background:#1c1c22 !important;
}
div[data-testid="stRadio"] > div > label[data-checked="true"] {
  background:rgba(255,45,120,0.12) !important;
  border-color:var(--magenta) !important; color:var(--text) !important;
  border-left-width:3px !important;
}
@keyframes card-enter {
  from { opacity:0; transform:translateY(14px) scale(0.98); }
  to   { opacity:1; transform:translateY(0) scale(1); }
}
.enter-card { animation:card-enter 0.3s cubic-bezier(0.19,1,0.22,1) both; }
.live-dot {
  display:inline-block; width:6px; height:6px; border-radius:50%;
  background:var(--magenta); animation:pulse-dot 1.4s infinite; vertical-align:middle; margin-right:6px;
}
@keyframes pulse-dot { 0%,100%{opacity:1;transform:scale(1)} 50%{opacity:0.4;transform:scale(0.7)} }
@keyframes fade-in { from{opacity:0} to{opacity:1} }
.fade-in { animation:fade-in 0.5s ease both; }
</style>
""")


# ─── UID ──────────────────────────────────────────────────────────────────────

def _uid():
    u = st.session_state.get("user")
    if isinstance(u, dict):
        uid = u.get("id") or u.get("user_id")
        if uid:
            try:
                return int(uid)
            except (TypeError, ValueError):
                pass
    try:
        uid = st.session_state.get("user_id")
        if uid:
            return int(uid)
    except (TypeError, ValueError):
        pass
    return None


def _debug_uid_info():
    return (
        f"session_state['user']={repr(st.session_state.get('user'))} | "
        f"session_state['user_id']={repr(st.session_state.get('user_id'))} | "
        f"resolved={_uid()}"
    )


def _show_persistent_db_error():
    err = st.session_state.get("wwyd_db_error", "")
    if err:
        st.error(f"⚠️ DB: {err}")


# ─── MISC HELPERS ─────────────────────────────────────────────────────────────

def _get_client():
    key = st.secrets.get("OPENAI_API_KEY", "")
    if not key:
        raise RuntimeError("OPENAI_API_KEY not found in Streamlit secrets.")
    return OpenAI(api_key=key)


def _fmt_num(n):
    return f"{n / 1000:.1f}k" if n >= 1000 else str(n)


def _time_ago(ts):
    diff = int(time.time() - ts)
    if diff < 3600:  return f"{diff // 60}m ago"
    if diff < 86400: return f"{diff // 3600}h ago"
    return f"{diff // 86400}d ago"


def _is_taboo(title, body):
    text = (title + " " + body).lower()
    return any(kw in text for kw in TABOO_KEYWORDS)


def _safe_json(raw):
    try:
        return json.loads(raw.strip().replace("```json", "").replace("```", "").strip())
    except Exception:
        return None


def _hd_signal_str(hd_answers):
    lines = []
    for q in HIDDEN_DESIRE_QUESTIONS:
        oid = hd_answers.get(q["id"])
        if oid in ("yes", "strongly"):
            lines.append(f"{q['signal']}:{'strong' if oid == 'strongly' else 'yes'}")
    return ", ".join(lines) if lines else "none"


def _question_hash(prompt_text: str) -> str:
    return hashlib.sha256(prompt_text.encode()).hexdigest()[:32]


# ─── REDDIT FETCH ─────────────────────────────────────────────────────────────
def _score_posts(posts: list, api_key: str) -> list:
    client = OpenAI(api_key=api_key)
    
    batch = "\n\n".join(
        f"[{i}] TITLE: {p['title']}\nBODY: {p['text'][:150]}"
        for i, p in enumerate(posts)
    )
    
    prompt = (
        "Score each Reddit post for a sexual desire quiz. Return ONLY a JSON array.\n"
        "Each item: {\"i\": index, \"tension\": 0-10, \"desire\": 0-10}\n\n"
        "tension = does this have a real situation with stakes? "
        "(venting/ranting = 0, clear scenario with a decision or revelation = 10)\n"
        "desire = does this involve attraction, fantasy, intimacy, or a sexual decision? "
        "(completely off-topic = 0, directly about sex/desire/fantasy = 10)\n\n"
        f"Posts:\n{batch}\n\n"
        "Return ONLY the JSON array, nothing else."
    )
    
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}]
    )
    
    scores = _safe_json(resp.choices[0].message.content)
    if not isinstance(scores, list):
        return posts  # fallback: keep all if scoring fails
    
    score_map = {s["i"]: s for s in scores}
    
    return [
        p for i, p in enumerate(posts)
        if score_map.get(i, {}).get("tension", 0) >= 7
        and score_map.get(i, {}).get("desire", 0) >= 7
    ]


def _get_reddit_token(client_id: str, client_secret: str) -> str:
    import requests
    r = requests.post(
        "https://www.reddit.com/api/v1/access_token",
        auth=(client_id, client_secret),
        data={"grant_type": "client_credentials"},
        headers={"User-Agent": "ViceVault/1.0"},
        timeout=5
    )
    return r.json().get("access_token", "")

def _fetch_one(sub):
    import requests
    client_id     = st.secrets.get("REDDIT_CLIENT_ID", "")
    client_secret = st.secrets.get("REDDIT_CLIENT_SECRET", "")

    if client_id and client_secret:
        token = _get_reddit_token(client_id, client_secret)
        url     = f"https://oauth.reddit.com/r/{sub}/hot.json?limit=25&include_over_18=1"
        headers = {
            "Authorization": f"bearer {token}",
            "User-Agent": "ViceVault/1.0"
        }
        urls_to_try = [url]
    else:
        url     = f"https://www.reddit.com/r/{sub}/hot.json?limit=20"
        headers = {"User-Agent": "Mozilla/5.0"}
        urls_to_try = [url, "https://api.allorigins.win/raw?url=" + url]

    for fetch_url in urls_to_try:
        try:
            r = requests.get(fetch_url, headers=headers, timeout=4)
            if not r.ok:
                continue
            data = r.json()
            if "contents" in data:
                data = json.loads(data["contents"])
            children = data.get("data", {}).get("children", [])
            posts = []
            for item in children:
                pd    = item.get("data", {})
                body  = pd.get("selftext", "")
                title = pd.get("title", "")
                if not body or len(body) < MIN_LENGTH:     continue
                if pd.get("score", 0) < MIN_SCORE:         continue
                if pd.get("stickied") or pd.get("pinned"): continue
                if body in ("[deleted]", "[removed]"):      continue
                snippet = body[:TEXT_CUTOFF].strip()
                if len(body) > TEXT_CUTOFF:
                    snippet += "…"
                posts.append({
                    "sub":      f"r/{sub}",
                    "avatar":   (pd.get("author") or "A")[0].upper(),
                    "user":     pd.get("author", "anonymous"),
                    "title":    title[:120],
                    "text":     snippet,
                    "upvotes":  _fmt_num(pd.get("score", 0)),
                    "comments": _fmt_num(pd.get("num_comments", 0)),
                    "time":     _time_ago(pd.get("created_utc", time.time())),
                    "url":      "https://reddit.com" + pd.get("permalink", ""),
                    "flair":    pd.get("link_flair_text") or sub.replace("_", " ").title(),
                })
            if posts:
                return posts
        except Exception:
            continue
    return []


@st.cache_data(ttl=600, show_spinner=False)
def fetch_posts():
    all_posts = []
    try:
        with ThreadPoolExecutor(max_workers=len(SUBREDDITS)) as pool:
            futures = {pool.submit(_fetch_one, sub): sub for sub in SUBREDDITS}
            for future in as_completed(futures, timeout=8):
                try:
                    all_posts.extend(future.result())
                except Exception:
                    pass
    except Exception:
        pass

    if all_posts:
        random.shuffle(all_posts)
        seen, unique = set(), []
        for p in all_posts:
            if p["title"] not in seen:
                seen.add(p["title"])
                unique.append(p)

        api_key = st.secrets.get("OPENAI_API_KEY", "")
        if api_key and unique:
            unique = _score_posts(unique[:20], api_key)

        if unique:
            return unique[: POST_COUNT * 2]

    pool = FALLBACK_POSTS.copy()
    random.shuffle(pool)
    return pool[:POST_COUNT]


# ─── QUESTION GENERATION ──────────────────────────────────────────────────────

GENDER_NEUTRAL_RULE = (
    "CRITICAL — gender-neutral and orientation-inclusive:\n"
    "  Use 'you', 'your partner', 'someone', 'they/them'.\n"
    "  NEVER assume the reader's gender, sexual orientation, or their partner's gender.\n"
    "  Do NOT write 'your boyfriend/girlfriend/husband/wife/he/she/him/her'.\n"
    "  The question must feel equally personal to ANY reader regardless of who they are."
)

ANSWER_OPTION_RULE = (
    "ANSWER OPTIONS — this is critical:\n"
    "Each option must feel like a private admission, not a preference on a survey.\n"
    "The reader should recognise themselves in exactly one option and feel slightly caught.\n"
    "Options must be specific — not 'I'd be open to it' but 'I've already thought about what I'd say if asked'.\n"
    "Use first person. Use 'I' and 'me'. No abstractions.\n"
    "Each option: one sentence, max 20 words, reads like something a real person would think but rarely say.\n"
    "Scale from most closed (pts:0) to fully on-board (pts:5) — but every option should feel like an honest person's real answer, not a strawman.\n"
    "pts:0 = real reluctance or firm boundary (not judgement, just honest)\n"
    "pts:2 = curious but holding back\n"
    "pts:3 = already thinking about it seriously\n"
    "pts:5 = decided, or has been here before"
)


@st.cache_data(ttl=3600, show_spinner=False)
def _generate_question_cached(post_url: str, post_title: str, post_text: str,
                               post_sub: str, api_key: str) -> dict:
    """Generate a quiz question from a Reddit post."""
    client = OpenAI(api_key=api_key)
    prompt = (
        f"You write questions for a desire and self-knowledge quiz called 'Read Between The Lines'.\n"
        f"This quiz is for adults on an 18+ platform. It should feel like a mirror, not a survey.\n\n"
        f"Reddit post from {post_sub}:\n"
        f"TITLE: {post_title}\n"
        f"EXCERPT: {post_text[:TEXT_CUTOFF]}\n\n"
        f"Write ONE question that puts the reader directly inside this specific situation.\n\n"
        f"Question rules:\n"
        f"- Reference a SPECIFIC emotional detail from the post, not just the topic\n"
        f"- The question should create a moment of recognition or slight discomfort\n"
        f"- Ask about what they'd actually feel or do — not what they 'think about' the topic\n"
        f"- The question should feel like it was written for them specifically\n"
        f"- {GENDER_NEUTRAL_RULE}\n\n"
        f"{ANSWER_OPTION_RULE}\n\n"
        f"Return ONLY JSON:\n"
        f'{{"prompt":"...","opts":[{{"t":"...","pts":0}},{{"t":"...","pts":2}},{{"t":"...","pts":3}},{{"t":"...","pts":5}}]}}'
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=400,
        messages=[{"role": "user", "content": prompt}],
    )
    raw  = resp.choices[0].message.content.strip()
    data = _safe_json(raw)
    if not isinstance(data, dict) or not data.get("prompt") or len(data.get("opts", [])) < 4:
        raise ValueError(f"Bad response: {raw[:80]}")
    return data


@st.cache_data(ttl=3600, show_spinner=False)
def _generate_scenario_from_scratch(slot_index: int, api_key: str) -> dict:
    """Ask the AI to invent a fresh, realistic scenario."""
    client = OpenAI(api_key=api_key)

    theme_hints = [
        "an attraction that develops inside an existing relationship — a slow realisation, not a sudden event",
        "a conversation a couple keeps almost having but never finishing",
        "a past experience that still surfaces at the wrong moments",
        "a fantasy one person has been carrying for years without naming it",
        "meeting someone at a specific moment and the timing being wrong in exactly one way",
        "discovering something unexpected about a partner that reframes everything before it",
        "a hypothetical that a couple laughs off but neither forgets",
        "the gap between what someone says they want and what they keep coming back to",
        "a boundary that has shifted without either person acknowledging it out loud",
        "a situation where honesty would be easier than silence but silence keeps winning",
    ]
    hint = theme_hints[slot_index % len(theme_hints)]

    prompt = (
        f"You write scenarios for a desire and self-knowledge quiz called 'Read Between The Lines'.\n"
        f"This quiz is for adults on an 18+ platform. It should feel like a mirror, not a survey.\n\n"
        f"Create ONE scenario about: {hint}\n\n"
        f"The scenario should:\n"
        f"- Feel like something a real person would post about anonymously at 1am\n"
        f"- Be 2-4 sentences — specific enough to feel real, open enough to feel universal\n"
        f"- End with a question that creates a moment of self-recognition or slight discomfort\n"
        f"- {GENDER_NEUTRAL_RULE}\n\n"
        f"{ANSWER_OPTION_RULE}\n\n"
        f"Return ONLY JSON:\n"
        f'{{"title":"Short evocative title, max 12 words, reads like a confession not a headline",'
        f'"text":"The 2-4 sentence scenario",'
        f'"prompt":"The question — should feel personal and slightly uncomfortable to answer honestly",'
        f'"opts":[{{"t":"...","pts":0}},{{"t":"...","pts":2}},{{"t":"...","pts":3}},{{"t":"...","pts":5}}]}}'
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=450,
        messages=[{"role": "user", "content": prompt}],
    )
    raw  = resp.choices[0].message.content.strip()
    data = _safe_json(raw)
    if not isinstance(data, dict) or not data.get("prompt") or len(data.get("opts", [])) < 4:
        raise ValueError(f"Bad AI scenario: {raw[:80]}")
    return {
        "sub":      "Vice Vault",
        "avatar":   "V",
        "user":     "anonymous",
        "flair":    "Scenario",
        "title":    data.get("title", "A scenario"),
        "text":     data.get("text", ""),
        "upvotes":  "—",
        "comments": "—",
        "time":     "now",
        "url":      "#",
        "prompt":   data["prompt"],
        "opts":     data["opts"],
    }


def _make_fallback_question(post):
    title = post.get("title", "this scenario")
    short = title[:60] + ("…" if len(title) > 60 else "")
    return {
        "prompt": f'Reading "{short}" — which of these is closest to your honest reaction?',
        "opts": [
            {"t": "I closed off immediately. This kind of thing isn't in my world.", "pts": 0},
            {"t": "I read it twice. I wouldn't act on it, but I didn't look away either.", "pts": 2},
            {"t": "This is more familiar to me than I'd admit in a normal conversation.", "pts": 3},
            {"t": "I've had a version of this conversation. Or I'm ready to.", "pts": 5},
        ],
    }


def _build_question_list(posts: list, api_key: str) -> list:
    """Build POST_COUNT questions from Reddit posts + AI-invented scenarios."""
    reddit_posts = [p for p in posts if "reddit.com" in p.get("url", "")]
    questions    = []

    reddit_results = [None] * len(reddit_posts)

    def _gen_reddit(idx, post):
        try:
            data = _generate_question_cached(
                post_url=post["url"], post_title=post["title"],
                post_text=post["text"], post_sub=post["sub"],
                api_key=api_key,
            )
            return idx, data
        except Exception:
            return idx, None

    if reddit_posts:
        with ThreadPoolExecutor(max_workers=min(len(reddit_posts), 8)) as pool:
            futures = {pool.submit(_gen_reddit, i, p): i for i, p in enumerate(reddit_posts)}
            try:
                for future in as_completed(futures, timeout=25):
                    try:
                        idx, data = future.result()
                        reddit_results[idx] = data
                    except Exception:
                        pass
            except Exception:
                pass

    for post, q_data in zip(reddit_posts, reddit_results):
        if q_data:
            questions.append({**post, **q_data})
        else:
            questions.append({**post, **_make_fallback_question(post)})

    needed = POST_COUNT - len(questions)
    if needed > 0:
        scratch_results = [None] * needed

        def _gen_scratch(slot_idx):
            try:
                scenario = _generate_scenario_from_scratch(
                    slot_index=len(questions) + slot_idx,
                    api_key=api_key,
                )
                return slot_idx, scenario
            except Exception:
                return slot_idx, None

        with ThreadPoolExecutor(max_workers=needed) as pool:
            futures = {pool.submit(_gen_scratch, i): i for i in range(needed)}
            try:
                for future in as_completed(futures, timeout=20):
                    try:
                        idx, scenario = future.result()
                        scratch_results[idx] = scenario
                    except Exception:
                        pass
            except Exception:
                pass

        for scenario in scratch_results:
            if scenario:
                questions.append(scenario)

    random.shuffle(questions)
    return questions[:POST_COUNT]


# ─── PROFILE + CATEGORY SCORING ───────────────────────────────────────────────

def generate_profile_and_categories(result_type, openness_pct, hd_answers,
                                    questions, answers, client) -> dict:
    hd_str = _hd_signal_str(hd_answers)

    pos, neg = [], []
    for qi, ai in enumerate(answers):
        if ai is None or qi >= len(questions):
            continue
        q   = questions[qi]
        opt = q.get("opts", [])
        if ai >= len(opt):
            continue
        pts  = opt[ai].get("pts", 0) if isinstance(opt[ai], dict) else 0
        text = (opt[ai].get("t", "") if isinstance(opt[ai], dict) else "")[:60]
        if pts >= 3:
            pos.append(f'"{q.get("title", "")[:40]}": {text}')
        elif pts == 0:
            neg.append(f'"{q.get("title", "")[:40]}": {text}')

    pos_str = "; ".join(pos[:4]) or "none"
    neg_str = "; ".join(neg[:4]) or "none"

    # Count strong HD signals for depth of profile
    strong_signals = [q["signal"] for q in HIDDEN_DESIRE_QUESTIONS
                      if hd_answers.get(q["id"]) == "strongly"]
    mild_signals   = [q["signal"] for q in HIDDEN_DESIRE_QUESTIONS
                      if hd_answers.get(q["id"]) == "yes"]

    prompt = (
        f"You are a desire profile analyst for an 18+ adult platform called Vice Vault.\n"
        f"Your job is to write a profile that feels uncomfortably accurate — like it was written specifically for this person.\n\n"
        f"User's data:\n"
        f"- Openness archetype: {result_type['name']} ({openness_pct}% openness index)\n"
        f"- Hidden desire signals (strong): {', '.join(strong_signals) or 'none'}\n"
        f"- Hidden desire signals (present): {', '.join(mild_signals) or 'none'}\n"
        f"- Resonated with: {pos_str}\n"
        f"- Rejected (DO NOT recommend these themes): {neg_str}\n\n"
        f"Your tasks — return ONE JSON object with exactly these keys:\n\n"
        f'1. "ranked_categories": Score EVERY category 0-10 based on how well it matches this person. '
        f"Rejected themes get 0. Be specific — not everything should score 5+.\n"
        f"   Categories: {json.dumps(ALL_PLATFORM_CATEGORIES)}\n\n"
        f'2. "recommendations": Exactly 5 recommendations. Rules:\n'
        f"   - Write like you know them, not like you're advising a stranger\n"
        f"   - Each rec should feel like something they're already close to but haven't named\n"
        f"   - Gender-neutral, non-judgmental, specific — not 'explore your boundaries'\n"
        f"   - 1-2 sentences. The second sentence should add something unexpected.\n"
        f"   - Do not recommend anything in the rejected list\n\n"
        f'3. "insight": One sentence, 15-25 words. The single most accurate thing about this person\'s desire profile. '
        f"Should feel like something they'd read twice.\n\n"
        f"Return ONLY valid JSON:\n"
        f'{{"ranked_categories":{{"CategoryName":score,...}},'
        f'"recommendations":["...","...","...","...","..."],'
        f'"insight":"..."}}'
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=2200,
        messages=[{"role": "user", "content": prompt}],
    )
    raw  = resp.choices[0].message.content.strip()
    data = _safe_json(raw)
    if not isinstance(data, dict):
        raise ValueError("Profile generation returned invalid JSON")

    raw_scores = data.get("ranked_categories", {})
    scored = sorted(
        [{"name": cat, "score": int(raw_scores.get(cat, 0))} for cat in ALL_PLATFORM_CATEGORIES],
        key=lambda x: -x["score"],
    )
    return {
        "ranked_categories": scored,
        "top25_names":       [c["name"] for c in scored[:25]],
        "recommendations":   data.get("recommendations", [])[:5],
        "insight":           data.get("insight", ""),
    }


# ─── COMMUNITY PULSE ──────────────────────────────────────────────────────────

def _render_community_pulse(q_hash: str, chosen_idx: int, opt_labels: list):
    """Record this answer and show an anonymous breakdown with the most surprising stat called out."""
    try:
        import database as db
        db.record_community_answer(q_hash, chosen_idx)
        tallies = db.get_community_answers(q_hash)
    except Exception:
        return

    total = sum(tallies.values())
    if total < 3:
        return

    # Find the most surprising stat: largest deviation from expected 25% (uniform)
    percentages = {i: round(tallies.get(i, 0) / total * 100) for i in range(len(opt_labels))}
    expected    = 100 // len(opt_labels)
    surprise_idx = max(percentages, key=lambda i: abs(percentages[i] - expected))
    surprise_pct = percentages[surprise_idx]

    # Write a contextual hook about the surprising stat
    if surprise_pct > 50:
        surprise_hook = f"More than half said: <em>{opt_labels[surprise_idx][:60]}…</em>"
    elif surprise_pct < 10:
        surprise_hook = f"Almost nobody said: <em>{opt_labels[surprise_idx][:60]}…</em>"
    elif surprise_idx == 0 and surprise_pct > 35:
        surprise_hook = f"{surprise_pct}% closed the door completely."
    elif surprise_idx == len(opt_labels) - 1 and surprise_pct > 35:
        surprise_hook = f"{surprise_pct}% were fully on board. That's higher than you'd expect."
    else:
        surprise_hook = f"The split here was more even than most questions. Worth noticing."

    st.html(f"""
<div style="margin-top:20px; margin-bottom:6px;">
  <div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:2px;
              text-transform:uppercase; color:var(--muted); margin-bottom:8px;">
    How {total} others answered
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:11px; color:var(--amber);
              font-style:italic; margin-bottom:12px; line-height:1.5;">
    {surprise_hook}
  </div>
</div>
""")

    for i, label in enumerate(opt_labels):
        count = tallies.get(i, 0)
        pct   = percentages[i]
        is_me = (i == chosen_idx)
        color = "var(--lime)" if is_me else ("var(--amber)" if i == surprise_idx else "var(--border)")
        label_color = "var(--lime)" if is_me else ("var(--amber)" if i == surprise_idx else "var(--soft)")
        st.html(f"""
<div style="margin-bottom:10px;">
  <div style="display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:4px; gap:8px;">
    <div style="font-family:'DM Sans',sans-serif; font-size:11px;
                color:{label_color}; max-width:82%; line-height:1.4;">
      {'▶ ' if is_me else ''}{label[:80]}{'…' if len(label) > 80 else ''}
    </div>
    <div style="font-family:'Space Mono',monospace; font-size:10px;
                color:{label_color}; flex-shrink:0; font-weight:{'700' if is_me else '400'};">
      {pct}%
    </div>
  </div>
  <div style="height:3px; background:var(--border); border-radius:2px;">
    <div style="width:{pct}%; height:100%; background:{color}; border-radius:2px; transition:width 0.4s ease;"></div>
  </div>
</div>
""")


# ─── STATE ────────────────────────────────────────────────────────────────────

_DEFAULTS = {
    "wwyd_phase":         "start",
    "wwyd_load_errors":   0,
    "wwyd_questions":     [],
    "wwyd_answers":       [],
    "wwyd_cur":           0,
    "wwyd_error":         "",
    "wwyd_db_error":      "",
    "wwyd_source":        "live",
    "wwyd_hd_cur":        0,
    "wwyd_hd_answers":    {},
    "wwyd_result_type":   {},
    "wwyd_openness_pct":  0,
    "wwyd_total_pts":     0,
    "wwyd_recs":          [],
    "wwyd_ranked_cats":   [],
    "wwyd_top25":         [],
    "wwyd_selected_cats": [],
    "wwyd_pulse_shown":   {},
    "wwyd_insight":       "",
}


def init_state():
    for k, v in _DEFAULTS.items():
        if k not in st.session_state:
            st.session_state[k] = v


def _wipe():
    for k in list(st.session_state.keys()):
        if k.startswith("wwyd_"):
            del st.session_state[k]


def hard_reset():
    _wipe()
    fetch_posts.clear()
    init_state()
    st.rerun()


# ─── DB SAVES ─────────────────────────────────────────────────────────────────

def _save_to_db(phase: str):
    uid = _uid()
    if not uid:
        st.session_state.wwyd_db_error = (
            f"Not saved ({phase}): could not resolve user ID. Debug: {_debug_uid_info()}"
        )
        return
    try:
        import database as db
        slim_questions = [
            {"title": q.get("title", ""), "sub": q.get("sub", ""),
             "prompt": q.get("prompt", ""), "opts": q.get("opts", [])}
            for q in st.session_state.get("wwyd_questions", [])
        ]
        saved = db.save_read_between_lines_v4(
            user_id=uid,
            phase=phase,
            result_name=st.session_state.get("wwyd_result_type", {}).get("name", ""),
            result_meta=st.session_state.get("wwyd_result_type", {}).get("meta", ""),
            openness_pct=st.session_state.get("wwyd_openness_pct", 0),
            total_pts=st.session_state.get("wwyd_total_pts", 0),
            questions=slim_questions,
            answers={
                "phase1": st.session_state.get("wwyd_answers", []),
                "phase2": st.session_state.get("wwyd_hd_answers", {}),
                "source": st.session_state.get("wwyd_source", "unknown"),
            },
            dim_scores={
                "ranked_cats": st.session_state.get("wwyd_ranked_cats", [])[:25],
                "top25":       st.session_state.get("wwyd_top25", []),
                "selected":    st.session_state.get("wwyd_selected_cats", []),
                "hd_signals":  _hd_signal_str(st.session_state.get("wwyd_hd_answers", {})),
                "insight":     st.session_state.get("wwyd_insight", ""),
                "hd_full": {
                    q["id"]: st.session_state.get("wwyd_hd_answers", {}).get(q["id"], "nope")
                    for q in HIDDEN_DESIRE_QUESTIONS
                },
            },
            recommendations=st.session_state.get("wwyd_recs", []),
        )
        st.session_state.wwyd_db_error = "" if saved else f"DB save returned False ({phase})."
    except Exception as e:
        st.session_state.wwyd_db_error = f"DB save exception ({phase}) uid={uid}: {e}"


def _update_selections_in_db(selected_cats: list):
    uid = _uid()
    if not uid:
        st.session_state.wwyd_db_error = (
            f"Selection not saved: could not resolve user ID. Debug: {_debug_uid_info()}"
        )
        return
    try:
        import database as db
        saved = db.update_rbtl_selected_categories(uid, selected_cats)
        if not saved:
            slim_questions = [
                {"title": q.get("title", ""), "sub": q.get("sub", ""),
                 "prompt": q.get("prompt", ""), "opts": q.get("opts", [])}
                for q in st.session_state.get("wwyd_questions", [])
            ]
            saved = db.save_read_between_lines_v4(
                user_id=uid, phase="category_selection",
                result_name=st.session_state.get("wwyd_result_type", {}).get("name", ""),
                result_meta=st.session_state.get("wwyd_result_type", {}).get("meta", ""),
                openness_pct=st.session_state.get("wwyd_openness_pct", 0),
                total_pts=st.session_state.get("wwyd_total_pts", 0),
                questions=slim_questions,
                answers={
                    "phase1": st.session_state.get("wwyd_answers", []),
                    "phase2": st.session_state.get("wwyd_hd_answers", {}),
                    "source": st.session_state.get("wwyd_source", "unknown"),
                },
                dim_scores={
                    "ranked_cats":         st.session_state.get("wwyd_ranked_cats", [])[:25],
                    "top25":               st.session_state.get("wwyd_top25", []),
                    "selected":            selected_cats,
                    "selection_confirmed": True,
                    "hd_signals":          _hd_signal_str(st.session_state.get("wwyd_hd_answers", {})),
                    "insight":             st.session_state.get("wwyd_insight", ""),
                },
                recommendations=st.session_state.get("wwyd_recs", []),
            )
        st.session_state.wwyd_db_error = "" if saved else f"Selection update failed uid={uid}."
    except Exception as e:
        st.session_state.wwyd_db_error = f"Selection update exception uid={uid}: {e}"


# ─── HEADER ───────────────────────────────────────────────────────────────────

def _render_header():
    st.html("""
<div style="border-bottom:1px solid var(--border); padding-bottom:20px; margin-bottom:28px;">
  <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:4px;
              text-transform:uppercase; color:var(--muted); margin-bottom:6px;">Vice Vault · Desire Quiz</div>
  <div style="font-family:'Bebas Neue',sans-serif; font-size:clamp(44px,9vw,68px);
              color:var(--text); letter-spacing:3px; line-height:0.92; margin-bottom:6px;">
    READ BETWEEN<br><span style="color:var(--magenta);">THE LINES</span>
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--muted); margin-top:4px;">
    Real scenarios. Hidden desires. Your full profile.
  </div>
</div>
""")
    _show_persistent_db_error()


# ─── PHASE: START ─────────────────────────────────────────────────────────────

def render_start():
    if st.session_state.wwyd_error:
        st.error(st.session_state.wwyd_error)
        st.session_state.wwyd_error = ""

    uid = _uid()
    if not uid:
        st.warning("Not logged in — results won't save to your profile.")

    st.html("""
<div class="enter-card">
  <div style="background:var(--card); border:1px solid var(--border);
              border-left:3px solid var(--magenta); border-radius:4px;
              padding:16px 18px; margin-bottom:10px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--magenta); margin-bottom:8px;">
      <span class="live-dot"></span>Phase 1 · Scenarios
    </div>
    <p style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--soft); line-height:1.75; margin:0;">
      7 situations pulled from real Reddit posts or invented from scratch by AI.
      Each one puts you directly inside the moment. After you answer, you'll see how
      everyone else responded — anonymously. The split is usually surprising.
    </p>
  </div>
  <div style="background:var(--card); border:1px solid var(--border);
              border-left:3px solid var(--amber); border-radius:4px;
              padding:16px 18px; margin-bottom:10px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--amber); margin-bottom:8px;">Phase 2 · Hidden Desires</div>
    <p style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--soft); line-height:1.75; margin:0;">
      15 statements that escalate. Starts easy. By the end, most people read at
      least one and think: I've never said that out loud.
    </p>
  </div>
  <div style="background:var(--card); border:1px solid var(--border);
              border-left:3px solid var(--cyan); border-radius:4px;
              padding:16px 18px; margin-bottom:20px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--cyan); margin-bottom:8px;">Phase 3 · Your Category Fingerprint</div>
    <p style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--soft); line-height:1.75; margin:0;">
      Every real platform category scored against your answers.
      A one-line insight that's either accurate or it isn't.
      You pick what goes into your profile.
    </p>
  </div>
  <div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:1px;
              text-transform:uppercase; color:var(--muted); text-align:center; margin-bottom:14px;">
    18+ only · Anonymous · Results saved to your profile
  </div>
</div>
""")
    if st.button("Begin →", use_container_width=True, type="primary", key="start_btn"):
        _wipe()
        st.session_state.wwyd_phase = "loading"
        st.rerun()


# ─── PHASE: LOADING ───────────────────────────────────────────────────────────

def render_loading():
    st.html("""
<div style="font-family:'Bebas Neue',sans-serif; font-size:36px; color:var(--text);
            letter-spacing:3px; margin-bottom:24px;">BUILDING YOUR QUIZ</div>
""")
    ph_bar    = st.empty()
    ph_status = st.empty()

    def upd(pct, msg):
        ph_bar.progress(pct)
        ph_status.caption(msg)

    try:
        upd(5, "Fetching live Reddit posts…")
        posts = fetch_posts()
        reddit_count  = len([p for p in posts if "reddit.com" in p.get("url", "")])
        scratch_count = max(0, POST_COUNT - reddit_count)

        status_msg = f"{reddit_count} Reddit post{'s' if reddit_count != 1 else ''}"
        if scratch_count:
            status_msg += f" + {scratch_count} AI scenario{'s' if scratch_count != 1 else ''} generating…"
        else:
            status_msg += " — generating questions…"
        upd(20, status_msg)

        api_key = st.secrets.get("OPENAI_API_KEY", "")
        if not api_key:
            st.session_state.wwyd_error = "OPENAI_API_KEY not found in secrets."
            st.session_state.wwyd_phase = "start"
            st.rerun()
            return

        upd(35, "All generating in parallel…")
        questions = _build_question_list(posts, api_key)

        upd(100, "Ready.")
        st.session_state.wwyd_questions   = questions
        st.session_state.wwyd_answers     = [None] * len(questions)
        st.session_state.wwyd_cur         = 0
        st.session_state.wwyd_pulse_shown = {}
        st.session_state.wwyd_source      = "live" if reddit_count else "ai"
        st.session_state.wwyd_phase       = "quiz"
        st.rerun()

    except Exception as e:
        st.session_state.wwyd_error = f"Failed to load: {e}. Please try again."
        st.session_state.wwyd_phase = "start"
        st.rerun()


# ─── PHASE: QUIZ ─────────────────────────────────────────────────────────────

def render_quiz():
    _show_persistent_db_error()
    questions = st.session_state.wwyd_questions
    cur       = st.session_state.wwyd_cur
    answers   = st.session_state.wwyd_answers

    if not questions or cur >= len(questions):
        st.session_state.wwyd_phase = "start"
        st.rerun()
        return

    if len(answers) < len(questions):
        answers = answers + [None] * (len(questions) - len(answers))
        st.session_state.wwyd_answers = answers

    q       = questions[cur]
    total   = len(questions)
    is_last = (cur == total - 1)
    q_hash  = _question_hash(q.get("prompt", q.get("title", str(cur))))

    segs = "".join(
        f'<div style="flex:1; height:3px; border-radius:2px; background:'
        f'{"var(--magenta)" if i < cur else "rgba(255,45,120,0.4)" if i == cur else "var(--border)"}"></div>'
        for i in range(total)
    )
    is_reddit = "reddit.com" in q.get("url", "")

    st.html(f"""
<div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:3px;
            text-transform:uppercase; color:var(--muted); margin-bottom:6px;">
  Phase 1 · Scenarios · {cur + 1} / {total}
</div>
<div style="display:flex; gap:3px; margin-bottom:20px;">{segs}</div>
""")

    st.html(f"""
<div class="enter-card" style="background:var(--card); border:1px solid var(--border);
            border-radius:4px; overflow:hidden; margin-bottom:14px;">
  <div style="display:flex; align-items:center; gap:10px; padding:11px 16px;
              border-bottom:1px solid var(--border);">
    <div style="width:28px; height:28px; border-radius:50%; background:var(--magenta);
                color:#fff; display:flex; align-items:center; justify-content:center;
                font-family:'DM Sans',sans-serif; font-size:12px; font-weight:700; flex-shrink:0;">
      {q['avatar']}
    </div>
    <div style="flex:1; min-width:0;">
      <div style="font-family:'Space Mono',monospace; font-size:10px; color:var(--magenta);">{q['sub']}</div>
      <div style="font-family:'DM Sans',sans-serif; font-size:10px; color:var(--muted);">
        u/{q['user']} · {q['time']}
      </div>
    </div>
    <div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:1px;
                padding:3px 8px; border:1px solid var(--border); color:var(--muted);
                text-transform:uppercase; border-radius:2px; white-space:nowrap; flex-shrink:0;">
      {q.get('flair', 'Post')}
    </div>
  </div>
  <div style="padding:14px 16px 10px;">
    <div style="font-family:'DM Sans',sans-serif; font-size:15px; font-weight:500;
                color:var(--text); line-height:1.5; margin-bottom:8px;">{q['title']}</div>
    <div style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--soft);
                line-height:1.8;">{q['text']}</div>
  </div>
  <div style="padding:8px 16px 10px; border-top:1px solid var(--border);
              display:flex; align-items:center; gap:14px;">
    <span style="font-family:'Space Mono',monospace; font-size:9px; color:var(--muted);">
      ▲ {q['upvotes']}
    </span>
    <span style="font-family:'Space Mono',monospace; font-size:9px; color:var(--muted);">
      💬 {q['comments']}
    </span>
    {'<a href="' + q["url"] + '" target="_blank" style="margin-left:auto;font-family:\'Space Mono\',monospace;font-size:9px;color:var(--cyan);text-decoration:none;letter-spacing:1px;text-transform:uppercase;">View on Reddit ↗</a>' if is_reddit else '<span style="margin-left:auto;font-family:\'Space Mono\',monospace;font-size:9px;color:var(--muted);">AI-generated scenario</span>'}
  </div>
</div>
<div style="font-family:'DM Sans',sans-serif; font-size:15px; font-style:italic;
            color:var(--amber); border-left:3px solid var(--amber); padding-left:14px;
            margin-bottom:18px; line-height:1.6;">{q['prompt']}</div>
""")

    opt_labels  = [(opt["t"] if isinstance(opt, dict) else opt) for opt in q["opts"]]
    current_sel = answers[cur]

    chosen = st.radio(
        label="Your answer",
        options=list(range(len(opt_labels))),
        format_func=lambda i: opt_labels[i],
        index=current_sel,
        key=f"quiz_radio_{cur}",
        horizontal=False,
    )

    if chosen != current_sel:
        a = list(st.session_state.wwyd_answers)
        a[cur] = chosen
        st.session_state.wwyd_answers = a

    # Community pulse — only after answer is selected
    if chosen is not None:
        _render_community_pulse(q_hash, chosen, opt_labels)

    st.html("<br>")
    col_back, col_next = st.columns(2)
    with col_back:
        if cur > 0:
            if st.button("← Back", key="quiz_back", use_container_width=True):
                st.session_state.wwyd_cur -= 1
                st.rerun()
    with col_next:
        btn_label = "Next: Hidden Desires →" if is_last else "Next →"
        answered  = st.session_state.wwyd_answers[cur] is not None
        if st.button(btn_label, key="quiz_next", disabled=not answered,
                     use_container_width=True, type="primary"):
            if is_last:
                st.session_state.wwyd_hd_cur = 0
                st.session_state.wwyd_phase  = "phase_transition"
            else:
                st.session_state.wwyd_cur += 1
            st.rerun()


# ─── PHASE: TRANSITION (between Phase 1 and Phase 2) ─────────────────────────

def render_phase_transition():
    """A brief beat between phases — creates anticipation rather than dead loading."""
    line = random.choice(PHASE_TRANSITIONS["to_hidden_desires"])

    st.html(f"""
<div class="enter-card fade-in" style="text-align:center; padding:60px 20px;">
  <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:4px;
              text-transform:uppercase; color:var(--muted); margin-bottom:20px;">
    Phase 1 complete
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:20px; color:var(--text);
              line-height:1.6; max-width:380px; margin:0 auto 32px; font-style:italic;">
    {line}
  </div>
  <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:3px;
              text-transform:uppercase; color:var(--amber); margin-bottom:8px;">
    Phase 2 · Hidden Desires
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:12px; color:var(--muted);
              margin-bottom:32px;">15 statements. They escalate.</div>
</div>
""")
    if st.button("Continue →", use_container_width=True, type="primary", key="transition_btn"):
        st.session_state.wwyd_phase = "hidden_desires"
        st.rerun()


# ─── PHASE: HIDDEN DESIRES ────────────────────────────────────────────────────

def render_hidden_desires():
    _show_persistent_db_error()
    total   = len(HIDDEN_DESIRE_QUESTIONS)
    answers = st.session_state.wwyd_hd_answers
    cur     = max(0, min(st.session_state.wwyd_hd_cur, total - 1))
    st.session_state.wwyd_hd_cur = cur

    q       = HIDDEN_DESIRE_QUESTIONS[cur]
    sel_id  = answers.get(q["id"])
    is_last = (cur == total - 1)
    tier    = q.get("tier", 1)

    # Tier-based accent color — escalates visually
    tier_colors = {1: "var(--soft)", 2: "var(--amber)", 3: "var(--magenta)",
                   4: "var(--magenta)", 5: "var(--lime)"}
    tier_labels = {1: "Warming up", 2: "Getting specific", 3: "The ones people don't say out loud",
                   4: "Deeper", 5: "The ones that catch people off guard"}
    accent = tier_colors.get(tier, "var(--amber)")
    tier_label = tier_labels.get(tier, "")

    segs = "".join(
        f'<div style="flex:1; height:3px; border-radius:2px; background:'
        f'{"var(--amber)" if i < cur else f"rgba(255,179,0,0.4)" if i == cur else "var(--border)"}"></div>'
        for i in range(total)
    )
    st.html(f"""
<div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:3px;
            text-transform:uppercase; color:var(--muted); margin-bottom:6px;">
  Phase 2 · Hidden Desires · {cur + 1} / {total}
</div>
<div style="display:flex; gap:2px; margin-bottom:20px;">{segs}</div>
<div class="enter-card" style="background:var(--card); border:1px solid var(--border);
            border-top:2px solid {accent}; border-radius:4px; padding:24px 24px 20px; margin-bottom:14px;">
  <div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:3px;
              text-transform:uppercase; color:{accent}; margin-bottom:12px; opacity:0.75;">
    {tier_label}
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:17px; font-style:italic;
              color:var(--text); line-height:1.7; font-weight:300;">{q['text']}</div>
</div>
<div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:2px;
            text-transform:uppercase; color:var(--muted); margin-bottom:10px; text-align:center;">
  How much does this resonate?
</div>
""")

    current_idx = HD_OPT_IDS.index(sel_id) if sel_id in HD_OPT_IDS else None
    chosen_idx  = st.radio(
        label="Resonance",
        options=list(range(len(HD_OPT_LABELS))),
        format_func=lambda i: HD_OPT_LABELS[i],
        index=current_idx,
        key=f"hd_radio_{cur}",
        horizontal=False,
    )

    if chosen_idx is not None:
        new_id = HD_OPT_IDS[chosen_idx]
        if new_id != sel_id:
            hd = dict(st.session_state.wwyd_hd_answers)
            hd[q["id"]] = new_id
            st.session_state.wwyd_hd_answers = hd
            if not is_last:
                st.session_state.wwyd_hd_cur += 1
                st.rerun()

    st.html("<br>")
    col_back, col_next = st.columns(2)
    with col_back:
        if cur > 0:
            if st.button("← Back", key="hd_back", use_container_width=True):
                st.session_state.wwyd_hd_cur -= 1
                st.rerun()
    with col_next:
        answered = q["id"] in st.session_state.wwyd_hd_answers
        if is_last:
            if st.button("Build My Profile →", key="hd_next_last",
                         disabled=not answered, use_container_width=True, type="primary"):
                st.session_state.wwyd_phase = "generating_profile"
                st.rerun()
        else:
            if st.button("Next →", key="hd_next_mid", disabled=not answered,
                         use_container_width=True,
                         type="primary" if answered else "secondary"):
                st.session_state.wwyd_hd_cur += 1
                st.rerun()


# ─── PHASE: GENERATING PROFILE ────────────────────────────────────────────────

def render_generating_profile():
    line = random.choice(PHASE_TRANSITIONS["to_profile"])
    st.html(f"""
<div style="font-family:'Bebas Neue',sans-serif; font-size:36px; color:var(--text);
            letter-spacing:3px; margin-bottom:8px;">BUILDING YOUR PROFILE</div>
<div style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--muted);
            font-style:italic; margin-bottom:24px;">{line}</div>
""")
    ph_bar    = st.empty()
    ph_status = st.empty()

    def upd(pct, s):
        ph_bar.progress(pct)
        ph_status.caption(s)

    try:
        upd(10, "Computing your Phase 1 score…")
        questions = st.session_state.wwyd_questions
        answers   = st.session_state.wwyd_answers
        hd_ans    = st.session_state.wwyd_hd_answers

        total_pts = sum(
            (q.get("opts", [])[a].get("pts", 0) if isinstance(q.get("opts", [])[a], dict) else 0)
            for q, a in zip(questions, answers)
            if a is not None and a < len(q.get("opts", []))
        )
        max_pts = sum(
            max((o.get("pts", 0) if isinstance(o, dict) else 0 for o in (q.get("opts") or [])), default=0)
            for q in questions
        )
        pct         = round((total_pts / max_pts) * 100) if max_pts else 0
        result_type = next(
            (r for r in RESULT_TYPES if r["min"] <= total_pts <= r["max"]),
            RESULT_TYPES[-1],
        )

        upd(30, "Reading your hidden desire signals…")
        client       = _get_client()

        upd(50, "Scoring every category against your profile…")
        profile_data = generate_profile_and_categories(
            result_type, pct, hd_ans, questions, answers, client
        )

        upd(90, "Saving to your profile…")
        st.session_state.wwyd_result_type   = result_type
        st.session_state.wwyd_openness_pct  = pct
        st.session_state.wwyd_total_pts     = total_pts
        st.session_state.wwyd_ranked_cats   = profile_data["ranked_categories"]
        st.session_state.wwyd_top25         = profile_data["top25_names"]
        st.session_state.wwyd_recs          = profile_data["recommendations"]
        st.session_state.wwyd_insight       = profile_data.get("insight", "")
        st.session_state.wwyd_selected_cats = list(profile_data["top25_names"])

        _save_to_db("profile_complete")

        db_err = st.session_state.get("wwyd_db_error", "")
        if db_err:
            st.error(f"⚠️ Save failed: {db_err}")
            time.sleep(2)

        upd(100, "Done.")
        time.sleep(0.1)
        st.session_state.wwyd_phase = "category_selector"
        st.rerun()

    except Exception as e:
        st.session_state.wwyd_error = f"Couldn't build your profile: {e}"
        st.session_state.wwyd_phase = "start"
        st.rerun()


# ─── PHASE: CATEGORY SELECTOR ────────────────────────────────────────────────

def render_category_selector():
    _show_persistent_db_error()
    ranked_cats = st.session_state.wwyd_ranked_cats
    top25_names = set(st.session_state.wwyd_top25)
    selected    = set(st.session_state.wwyd_selected_cats)
    pct         = st.session_state.get("wwyd_openness_pct", 0)
    result_type = st.session_state.get("wwyd_result_type", {})
    insight     = st.session_state.get("wwyd_insight", "")

    st.html(f"""
<div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:3px;
            text-transform:uppercase; color:var(--muted); margin-bottom:6px;">
  Phase 3 · Your Category Fingerprint
</div>
<div style="background:var(--card); border:1px solid var(--border);
            border-top:2px solid var(--cyan); border-radius:4px; padding:18px 20px; margin-bottom:16px;">
  <div style="display:flex; align-items:flex-start; justify-content:space-between; flex-wrap:wrap; gap:12px; margin-bottom:14px;">
    <div style="flex:1; min-width:200px;">
      <div style="font-family:'Bebas Neue',sans-serif; font-size:22px; color:var(--text);
                  letter-spacing:2px;">{result_type.get('icon','')} {result_type.get('name','')}</div>
      <div style="font-family:'Space Mono',monospace; font-size:8px; color:var(--magenta);
                  letter-spacing:1px; text-transform:uppercase; margin-top:2px;">
        {result_type.get('meta','')}
      </div>
    </div>
    <div style="background:var(--surface); border:1px solid var(--border); border-radius:3px;
                padding:8px 14px; text-align:center; flex-shrink:0;">
      <div style="font-family:'Bebas Neue',sans-serif; font-size:28px; color:var(--text);">{pct}</div>
      <div style="font-family:'Space Mono',monospace; font-size:8px; color:var(--muted);
                  text-transform:uppercase; letter-spacing:1px;">openness %</div>
    </div>
  </div>
  {f'<div style="font-family:\'DM Sans\',sans-serif; font-size:13px; color:var(--amber); font-style:italic; line-height:1.6; border-left:2px solid var(--amber); padding-left:12px; margin-bottom:12px;">{insight}</div>' if insight else ''}
  <div style="font-family:'DM Sans',sans-serif; font-size:12px; color:var(--muted); line-height:1.65;">
    Every real platform category scored against your answers.
    <span style="color:var(--lime);">Lime = AI top 25 picks for you.</span>
    Toggle anything you want — this is your profile, not a recommendation.
  </div>
</div>
<div style="font-family:'Space Mono',monospace; font-size:8px; letter-spacing:2px;
            text-transform:uppercase; color:var(--muted); margin-bottom:14px;">
  {len(selected)} selected
</div>
""")

    cols = st.columns(3)
    for idx, cat_info in enumerate(ranked_cats):
        cat_name  = cat_info["name"]
        cat_score = cat_info["score"]
        is_top25  = cat_name in top25_names
        is_sel    = cat_name in selected
        btn_label = f"✓ {cat_name}" if is_sel else (f"◆ {cat_name}" if is_top25 else cat_name)

        with cols[idx % 3]:
            if st.button(btn_label, key=f"cat_{idx}", use_container_width=True,
                         type="primary" if is_sel else "secondary"):
                new_sel = set(st.session_state.wwyd_selected_cats)
                if is_sel:
                    new_sel.discard(cat_name)
                else:
                    new_sel.add(cat_name)
                st.session_state.wwyd_selected_cats = list(new_sel)
                st.rerun()

            if cat_score > 0:
                bar_color = "var(--lime)" if is_top25 else "var(--border)"
                st.html(f"""
<div style="height:2px; background:var(--border); border-radius:1px; margin:-6px 0 8px;">
  <div style="width:{min(100, cat_score * 10)}%; height:100%;
              background:{bar_color}; border-radius:1px;"></div>
</div>
""")

    st.html("<br>")
    if st.button("See My Full Profile →", use_container_width=True, type="primary",
                 disabled=(len(selected) == 0), key="cat_next"):
        _update_selections_in_db(list(selected))
        st.session_state.wwyd_phase = "result"
        st.rerun()


# ─── PHASE: RESULT ────────────────────────────────────────────────────────────

def render_result():
    _show_persistent_db_error()
    result_type = st.session_state.get("wwyd_result_type") or RESULT_TYPES[0]
    pct         = st.session_state.get("wwyd_openness_pct", 0)
    sel_cats    = st.session_state.get("wwyd_selected_cats", [])
    recs        = st.session_state.get("wwyd_recs", [])
    ranked_cats = st.session_state.get("wwyd_ranked_cats", [])
    hd_ans      = st.session_state.get("wwyd_hd_answers", {})
    insight     = st.session_state.get("wwyd_insight", "")

    # Three-line result breakdown instead of one paragraph
    hook   = result_type.get("hook", "")
    signal = result_type.get("signal", "")
    tell   = result_type.get("tell", "")

    st.html(f"""
<div class="enter-card" style="background:var(--card); border:1px solid var(--border);
            border-top:3px solid var(--magenta); border-radius:4px;
            padding:28px 24px; margin-bottom:14px;">
  <div style="font-size:42px; margin-bottom:10px;">{result_type['icon']}</div>
  <div style="font-family:'Bebas Neue',sans-serif; font-size:clamp(28px,6vw,46px);
              letter-spacing:3px; color:var(--text); line-height:1.05; margin-bottom:4px;">
    {result_type['name'].upper()}
  </div>
  <div style="font-family:'Space Mono',monospace; font-size:10px; letter-spacing:2px;
              color:var(--magenta); text-transform:uppercase; margin-bottom:24px;">
    {result_type['meta']}
  </div>

  <div style="border-top:1px solid var(--border); padding-top:18px; margin-bottom:16px;">
    <div style="font-family:'DM Sans',sans-serif; font-size:14px; color:var(--text);
                line-height:1.75; margin-bottom:14px;">{hook}</div>
    <div style="font-family:'DM Sans',sans-serif; font-size:13px; color:var(--soft);
                line-height:1.75; margin-bottom:14px; border-left:2px solid var(--border);
                padding-left:12px;">{signal}</div>
    <div style="font-family:'Space Mono',monospace; font-size:10px; color:var(--amber);
                line-height:1.65; letter-spacing:0.5px;">{tell}</div>
  </div>

  {f'<div style="background:var(--surface); border:1px solid var(--amber); border-radius:3px; padding:14px 16px; margin-top:4px;"><div style="font-family:\'Space Mono\',monospace; font-size:8px; letter-spacing:2px; text-transform:uppercase; color:var(--amber); margin-bottom:6px;">One-line read</div><div style="font-family:\'DM Sans\',sans-serif; font-size:14px; color:var(--text); font-style:italic; line-height:1.65;">{insight}</div></div>' if insight else ''}

  <div style="background:var(--surface); border:1px solid var(--border); border-radius:3px;
              padding:14px; margin-top:16px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--muted); margin-bottom:8px;">Openness Index</div>
    <div style="height:4px; background:var(--border); border-radius:2px; margin-bottom:8px;">
      <div style="width:{pct}%; height:100%;
                  background:linear-gradient(90deg, var(--amber), var(--magenta));
                  border-radius:2px;"></div>
    </div>
    <div style="display:flex; justify-content:space-between; align-items:center;">
      <span style="font-family:'Space Mono',monospace; font-size:8px; color:var(--muted);">Closed off</span>
      <span style="font-family:'Bebas Neue',sans-serif; font-size:32px; color:var(--text);">
        {pct}<span style="font-size:14px; color:var(--muted);"> / 100</span>
      </span>
      <span style="font-family:'Space Mono',monospace; font-size:8px; color:var(--muted);">Wide open</span>
    </div>
  </div>
</div>
""")

    # Hidden desire signals — starred for strong, sorted by tier
    strong = sorted(
        [q for q in HIDDEN_DESIRE_QUESTIONS if hd_ans.get(q["id"]) in ("yes", "strongly")],
        key=lambda q: (-(3 if hd_ans.get(q["id"]) == "strongly" else 2), q.get("tier", 1)),
    )
    if strong:
        sigs_html = "".join(
            f'<div style="display:flex; gap:12px; align-items:flex-start; padding:10px 0;'
            f' border-bottom:1px solid var(--border);">'
            f'<span style="color:{"var(--magenta)" if hd_ans.get(q["id"]) == "strongly" else "var(--amber)"};'
            f' flex-shrink:0; margin-top:3px; font-size:10px;">'
            f'{"★" if hd_ans.get(q["id"]) == "strongly" else "◆"}</span>'
            f'<div style="font-family:\'DM Sans\',sans-serif; font-size:12px; color:var(--soft);'
            f' line-height:1.7; font-style:italic;">{q["text"]}</div></div>'
            for q in strong
        )
        st.html(f"""
<div style="background:var(--card); border:1px solid var(--border); border-radius:4px;
            padding:18px; margin-bottom:12px;">
  <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--amber);">Hidden Desire Signals</div>
    <div style="font-family:'Space Mono',monospace; font-size:9px; color:var(--muted);">
      {len([q for q in strong if hd_ans.get(q['id']) == 'strongly'])} strong · {len([q for q in strong if hd_ans.get(q['id']) == 'yes'])} present
    </div>
  </div>
  {sigs_html}
</div>
""")

    # Top 10 categories
    if ranked_cats:
        top10     = [c for c in ranked_cats[:10] if c["score"] > 0]
        max_score = ranked_cats[0]["score"] if ranked_cats else 1
        bars_html = "".join(
            f'<div style="display:flex; align-items:center; gap:10px; margin-bottom:10px;">'
            f'<div style="font-family:\'Space Mono\',monospace; font-size:9px;'
            f' color:{"var(--lime)" if c["name"] in sel_cats else "var(--soft)"};'
            f' width:150px; flex-shrink:0; white-space:nowrap; overflow:hidden;'
            f' text-overflow:ellipsis; text-transform:uppercase; letter-spacing:1px;">'
            f'{"✓ " if c["name"] in sel_cats else ""}{c["name"]}</div>'
            f'<div style="flex:1; height:3px; background:var(--border); border-radius:2px;">'
            f'<div style="width:{min(100, round(c["score"] / max_score * 100))}%; height:100%;'
            f' background:{"var(--lime)" if c["name"] in sel_cats else "var(--muted)"};'
            f' border-radius:2px;"></div></div>'
            f'<div style="font-family:\'Space Mono\',monospace; font-size:8px; color:var(--muted);'
            f' width:20px; text-align:right;">{c["score"]}</div>'
            f'</div>'
            for c in top10
        )
        st.html(f"""
<div style="background:var(--card); border:1px solid var(--border); border-radius:4px;
            padding:18px; margin-bottom:12px;">
  <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:14px;">
    <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
                text-transform:uppercase; color:var(--cyan);">Content Fingerprint · Top 10</div>
    <div style="font-family:'Space Mono',monospace; font-size:9px; color:var(--muted);">
      {len(sel_cats)} selected
    </div>
  </div>
  {bars_html}
</div>
""")

    # Recommendations — each one specific, not a category header
    if recs:
        recs_html = "".join(
            f'<div style="padding:14px 0; border-bottom:1px solid var(--border);">'
            f'<div style="font-family:\'Space Mono\',monospace; font-size:8px; letter-spacing:2px;'
            f' text-transform:uppercase; color:var(--magenta); margin-bottom:6px;">0{i+1}</div>'
            f'<div style="font-family:\'DM Sans\',sans-serif; font-size:13px; color:var(--soft);'
            f' line-height:1.8;">{r}</div></div>'
            for i, r in enumerate(recs)
        )
        st.html(f"""
<div style="background:var(--card); border:1px solid var(--border); border-radius:4px;
            padding:18px; margin-bottom:16px;">
  <div style="font-family:'Space Mono',monospace; font-size:9px; letter-spacing:2px;
              text-transform:uppercase; color:var(--magenta); margin-bottom:4px;">
    Things Worth Exploring
  </div>
  <div style="font-family:'DM Sans',sans-serif; font-size:11px; color:var(--muted);
              margin-bottom:12px;">Based on what you actually answered — not just your archetype.</div>
  {recs_html}
</div>
""")

    share = (
        f"Read Between The Lines — Vice Vault\n\n"
        f"Result: {result_type['name']}\n\"{result_type['meta']}\"\n"
        f"Openness Index: {pct}%\n\n"
        f"{result_type.get('hook','')}\n"
        f"{result_type.get('signal','')}\n"
        f"{result_type.get('tell','')}\n"
    )
    if insight:
        share += f"\nOne-line read: {insight}\n"
    if strong:
        share += "\nSignals: " + ", ".join(q["signal"] for q in strong[:5]) + "\n"
    if sel_cats:
        share += "\nMy categories: " + ", ".join(sel_cats[:10]) + "\n"
    if recs:
        share += "\nRecommendations:\n" + "\n".join(f"· {r}" for r in recs[:3])

    col1, col2 = st.columns(2)
    with col1:
        if st.button("↺ Try Again", use_container_width=True, key="try_again"):
            hard_reset()
    with col2:
        st.download_button(
            "↓ Save Result",
            data=share,
            file_name="rbtl_result.txt",
            mime="text/plain",
            use_container_width=True,
            key="save_result",
        )


# ─── ENTRY POINT ─────────────────────────────────────────────────────────────

def what_would_you_do_page():
    inject_css()
    init_state()
    _render_header()

    phase = st.session_state.wwyd_phase

    if   phase == "start":              render_start()
    elif phase == "loading":            render_loading()
    elif phase == "quiz":               render_quiz()
    elif phase == "phase_transition":   render_phase_transition()
    elif phase == "hidden_desires":     render_hidden_desires()
    elif phase == "generating_profile": render_generating_profile()
    elif phase == "category_selector":  render_category_selector()
    elif phase == "result":             render_result()
    else:
        _wipe()
        init_state()
        st.rerun()
